apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mariadb-auth-service.yaml
  - mariadb-auth-statefulset.yaml
  - mariadb-tire-service.yaml
  - mariadb-tire-statefulset.yaml
  - mariadb-order-service.yaml
  - mariadb-order-statefulset.yaml
  - auth-service.yaml
  - auth-deployment.yaml
  - tire-service.yaml
  - tire-deployment.yaml
  - order-service.yaml
  - order-deployment.yaml
  - gateway-service.yaml
  - gateway-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
