apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mariadb-service.yaml
  - mariadb-statefulset.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - gateway-service.yaml
  - gateway-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
