apiVersion: v1
kind: Service
metadata:
  name: mariadb-order
  labels:
    app: mariadb-order
spec:
  clusterIP: None
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb-order
