apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: mariadb
  DB_PORT: "3306"
  DB_NAME: tire_shop
  JWT_EXPIRATION_SECONDS: "3600"
  JWT_REFRESH_EXPIRATION_SECONDS: "1209600"
  JWT_REFRESH_COOKIE_NAME: refreshToken
  JWT_REFRESH_COOKIE_SECURE: "false"
  JWT_REFRESH_COOKIE_SAME_SITE: Lax
  TIRE_BASE_URL: http://tire-service:8080
