apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef: # 去查 ConfigMap
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: JWT_EXPIRATION_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_EXPIRATION_SECONDS
            - name: JWT_REFRESH_EXPIRATION_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_REFRESH_EXPIRATION_SECONDS
            - name: JWT_REFRESH_COOKIE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_REFRESH_COOKIE_NAME
            - name: JWT_REFRESH_COOKIE_SECURE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_REFRESH_COOKIE_SECURE
            - name: JWT_REFRESH_COOKIE_SAME_SITE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_REFRESH_COOKIE_SAME_SITE
            - name: BACKEND_AUTH_ENDPOINTS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_AUTH_ENDPOINTS_ENABLED
            - name: BACKEND_TIRE_ENDPOINTS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_TIRE_ENDPOINTS_ENABLED
