apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
namespace: tire-ordering
images:
  - name: ghcr.io/fy20047/tire-ordering-system/backend
    newTag: 8996fe806b7c62d5d0b4450482fc4a4086f5c2ce
  - name: ghcr.io/fy20047/tire-ordering-system/frontend
    newTag: 8996fe806b7c62d5d0b4450482fc4a4086f5c2ce
patches:
  - path: frontend-nodeport.yaml
  - path: backend-scale.yaml
  - path: frontend-scale.yaml
