apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- ingress.yaml
- app-config.yaml
- app-sealedsecret.yaml
- db-sealedsecret.yaml
- hpa-frontend.yaml
- pdb-frontend.yaml
- resourcequota.yaml
- limitrange.yaml
namespace: tire-ordering
images:
- name: ghcr.io/fy20047/tire-ordering-system-microservices/api-gateway
  newTag: 9b09394e4da6b24c93de1af1cc4d3a6cdbc282aa
- name: ghcr.io/fy20047/tire-ordering-system-microservices/auth-service
  newTag: 9b09394e4da6b24c93de1af1cc4d3a6cdbc282aa
- name: ghcr.io/fy20047/tire-ordering-system-microservices/frontend
  newTag: 9b09394e4da6b24c93de1af1cc4d3a6cdbc282aa
- name: ghcr.io/fy20047/tire-ordering-system-microservices/order-service
  newTag: 9b09394e4da6b24c93de1af1cc4d3a6cdbc282aa
- name: ghcr.io/fy20047/tire-ordering-system-microservices/tire-service
  newTag: 9b09394e4da6b24c93de1af1cc4d3a6cdbc282aa
patches:
- path: frontend-nodeport.yaml
- path: frontend-scale.yaml
- path: auth-configmap-env.yaml
- path: tire-configmap-env.yaml
- path: order-configmap-env.yaml
- path: frontend-resources.yaml
