apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  template:
    spec:
      containers:
        - name: order-service
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_DB_NAME
            - name: JWT_EXPIRATION_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_EXPIRATION_SECONDS
            - name: TIRE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TIRE_BASE_URL
