apiVersion: apps/v1
kind: Deployment
metadata:
  name: tire-service
spec:
  template:
    spec:
      containers:
        - name: tire-service
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TIRE_DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TIRE_DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TIRE_DB_NAME
            - name: JWT_EXPIRATION_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_EXPIRATION_SECONDS
